### PR TITLE
chore(app): display available pools

### PR DESCRIPTION
**Pull request by MattNguyen**
+ run lint:fix

### CODE REVIEW

**Comment by desamtralized** [comment]
@MattNguyen , this was already implemented in https://github.com/yieldi-labs/yieldi-web/pull/28.

I suggest we close #31 unmerged.

**Review by desamtralized — CHANGES_REQUESTED** [review]
This was implemented in #28, I suggest we close this PR unmerged.

**Comment by MattNguyen** [comment]
> This was implemented in #28, I suggest we close this PR unmerged.

why didn't you merge that in separately? this is an issue *now*. 

1. this is completely separate linear issue
2. you did not mark the status as in progress. it was left todo
3. what signal did you provide that indicated you were working on this?

**Comment by desamtralized** [comment]
> > This was implemented in #28, I suggest we close this PR unmerged.
> 
> why didn't you merge that in separately? this is an issue _now_.
> 
> 1. this is completely separate linear issue
> 2. you did not mark the status as in progress. it was left todo
> 3. what signal did you provide that indicated you were working on this?

1. agreed, was thinking of piggybacking it, didn't think there was a linear issue (should have checked that). 
2. you're right, I didn't check linear, my bad.
3. none, sorry.

**Pull request closed without merging**
